name: todo_list_provider
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  sqflite: ^2.4.1
  synchronized: ^3.3.0+3
  path: ^1.9.0
  sqflite_common: ^2.5.4+6
  google_fonts: ^6.2.1
  flutter_signin_button: ^2.0.0
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  cloud_firestore: ^5.6.3
  validatorless: ^1.2.4
  flutter_overlay_loader: ^2.0.0
  google_sign_in: ^6.2.2
  date_picker_timeline: ^1.2.6
  intl: 0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: TodoListIcons
      fonts:
        - asset: assets/fonts/TodoListIcons.ttf
